before_script:
  - echo "Before script"
  - echo $CI_BUILD_REF
  - echo $CI_PROJECT_DIR
  - echo $CI_COMMIT_TAG

stages:
  - start

start-job:
  stage: start
  image: docker.io/ubuntu:latest
  script:
    - echo "Starting flask app"
    - pwd
    - ls -R
    - mkdir -p /opt/flask_app
    - cp -R templates /opt/flask_app
    - cp -R static /opt/flask_app
    - cp -R app.py /opt/flask_app
    - ls -R
    - apt-get update
    - apt-get install build-essential checkinstall
    - apt-get install libreadline-gplv2-dev libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-de
    - cd /usr/src
    - wget https://www.python.org/ftp/python/2.7.14/Python-2.7.14.tgz
    - tar xzf Python-2.7.14.tgz
    - cd Python-2.7.14
    - ./configure
    - make altinstall
    - python2.7 -V
    - pip install flask
    - pip install urllib2
    - pip install xmltodict
    - pip install json
    - cd /opt/flask_app
    - flask stop
    - export FLASK_APP=app.py
    - flask run
    
  tags:
    - docker-linux
