image: docker:latest

variables:
  DOCKER_REGISTRY: "pocdv01bvla:5001"
  VERSION_NUMBER: "0.1.0"

stages:
  - build
  - tag
  - push

build-job:
  stage: build
  script:
    - docker info
    - docker build -t healthnow/test-automation-portal:$VERSION_NUMBER .
  only:
    - master
  tags:
    - docker-linux

tag-job:
  stage: tag
  script:
    - docker images
    - docker tag healthnow/test-automation-portal:$VERSION_NUMBER  $DOCKER_REGISTRY/healthnow/test-automation-portal:$VERSION_NUMBER 
    - docker images
  only:
    - master
  tags:
    - docker-linux

push-job:
  stage: push
  script:
    - docker images
    - docker push $DOCKER_REGISTRY/healthnow/test-automation-portal:$VERSION_NUMBER
  only:
    - master
  tags:
    - docker-linux
