image: docker:latest

variables:
  DOCKER_REGISTRY: "pocdv01bvla:5001"

stages:
  - build
  - tag
  - push

build-job:
  stage: build
  script:
    - docker info
    - docker build -t healthnow/test-automation-portal .
  only:
    - master
  tags:
    - docker-linux

tag-job:
  stage: tag
  script:
    - docker images
    - docker tag healthnow/test-automation-portal  $DOCKER_REGISTRY/healthnow/test-automation-portal 
    - docker images
  only:
    - master
  tags:
    - docker-linux

push-job:
  stage: push
  script:
    - docker images
    - docker push $DOCKER_REGISTRY/healthnow/test-automation-portal
  only:
    - master
  tags:
    - docker-linux
